sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t paulosullivan22/docker-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true paulosullivan22/docker-kubernetes npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-kubernetes-env"
  env: "Dockerkubernetesenv-env"
  bucket_name: "elasticbeanstalk-us-east-1-907188092423"
  bucket_path: "docker-kubernetes-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
